### ISSUE TITLE
[0.2.5] `ArrayIndexOutOfBoundsException` for `hexerei:mixing_cauldron_entity`

### ISSUE THREAD

**Issue by thimblebird** [JoeFoxe/Hexerei-0.2.1-1.18#18]
crash report:
[crash-2022-11-27_20.30.34-server.txt](https://github.com/JoeFoxe/Hexerei-1.19/files/10099059/crash-2022-11-27_20.30.34-server.txt)

**Comment by thimblebird** [comment]
aight. there's some stuff going on with Quark. this config isn't working:
[quark-common.txt](https://github.com/JoeFoxe/Hexerei-1.19/files/10099470/quark-common.txt)

the default config works. couldn't figure out what's going on yet.

//edit:
Setting the "Mobs" category to `false` (everything else default) crashes the server on world load/placing a Mixing Cauldron (just make sure to restart Minecraft when changing the config):
```toml
[categories]
	Automation = true
	Building = true
	Management = true
	Tools = true
	Tweaks = true
	World = true
	Mobs = false
	Client = true
	Experimental = true
	Oddities = true
```

//edit²:
it's the crab brewing config; setting it to `false` results in the crash:
```toml
	[mobs.crabs]
		"Enable Brewing" = false
```

so, is this an issue to report to Quark?
